# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DA', '0013_xuewei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans_wenda',
            name='ans_con',
            field=models.CharField(max_length=1000),
        ),
    ]
